"""
Regenerates src/components/icons/uiconPaths.ts: outlines of Flaticon UIcons
(regular, rounded) as SVG path data, so the app ships a few dozen icons as
inline SVG instead of the whole 385 KB icon font.

    python scripts/uicons.py                 # rebuild the current set
    python scripts/uicons.py toothbrush bed  # add icons, then rebuild

Names are the part after `fi-rr-` on https://www.flaticon.com/uicons. Needs
fontTools and brotli (pip install fonttools brotli) and npm on the PATH; the
font comes from the @flaticon/flaticon-uicons package, fetched into a temp
folder rather than installed.

UIcons are free with attribution: "Uicons by Flaticon".
"""
import glob
import os
import re
import subprocess
import sys
import tarfile
import tempfile

from fontTools.pens.basePen import BasePen
from fontTools.ttLib import TTFont

PACKAGE = "@flaticon/flaticon-uicons@3.3.1"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "src", "components", "icons", "uiconPaths.ts")
CACHE = os.path.join(tempfile.gettempdir(), "flaticon-uicons-3.3.1")


def font_path():
    found = glob.glob(os.path.join(CACHE, "package", "css", "uicons-regular-rounded-*.woff2"))
    if not found:
        os.makedirs(CACHE, exist_ok=True)
        tgz = subprocess.run(
            ["npm", "pack", PACKAGE, "--silent"], cwd=CACHE, capture_output=True, text=True,
            check=True, shell=os.name == "nt",
        ).stdout.strip().splitlines()[-1]
        with tarfile.open(os.path.join(CACHE, tgz)) as tar:
            tar.extractall(CACHE, filter="data")
        found = glob.glob(os.path.join(CACHE, "package", "css", "uicons-regular-rounded-*.woff2"))
    return found[0]


class CompactPathPen(BasePen):
    """Relative commands on whole units of the font's 300-unit em, y flipped
    for SVG. Deltas come from already-rounded points, so nothing drifts."""

    def __init__(self, glyph_set, height):
        super().__init__(glyph_set)
        self.height = height
        self.parts = []
        self.cur = (0, 0)
        self.start = (0, 0)
        self.last_cmd = None

    def _pt(self, p):
        return (round(p[0]), round(self.height - p[1]))

    def _emit(self, cmd, *nums):
        text = "" if cmd == self.last_cmd and cmd != "m" else cmd
        for n in nums:
            s = str(n)
            # A minus sign already separates numbers; otherwise a space is needed.
            if text and not s.startswith("-") and text[-1].isdigit():
                text += " "
            elif not text and not s.startswith("-") and self.parts and self.parts[-1][-1].isdigit():
                text += " "
            text += s
        self.parts.append(text)
        self.last_cmd = "l" if cmd == "m" else cmd

    def _rel(self, p):
        return (p[0] - self.cur[0], p[1] - self.cur[1])

    def _moveTo(self, p):
        p = self._pt(p)
        self._emit("m", *self._rel(p))
        self.cur = self.start = p

    def _lineTo(self, p):
        p = self._pt(p)
        dx, dy = self._rel(p)
        if dx == 0 and dy == 0:
            return
        if dy == 0:
            self._emit("h", dx)
        elif dx == 0:
            self._emit("v", dy)
        else:
            self._emit("l", dx, dy)
        self.cur = p

    def _qCurveToOne(self, p1, p2):
        p1, p2 = self._pt(p1), self._pt(p2)
        self._emit("q", *self._rel(p1), *self._rel(p2))
        self.cur = p2

    def _curveToOne(self, p1, p2, p3):
        p1, p2, p3 = self._pt(p1), self._pt(p2), self._pt(p3)
        self._emit("c", *self._rel(p1), *self._rel(p2), *self._rel(p3))
        self.cur = p3

    def _closePath(self):
        self.parts.append("z")
        self.last_cmd = "z"
        self.cur = self.start

    _endPath = _closePath

    def path(self):
        return "".join(self.parts)


def existing_names():
    if not os.path.exists(OUT):
        return []
    return re.findall(r'^  "([a-z0-9-]+)":', open(OUT, encoding="utf-8").read(), re.M)


def main():
    names = sorted(set(existing_names()) | set(sys.argv[1:]))
    font = TTFont(font_path())
    glyphs = font.getGlyphSet()
    em = font["head"].unitsPerEm
    missing = [n for n in names if f"fi-rr-{n}" not in glyphs]
    if missing:
        sys.exit("Not in UIcons regular rounded: " + ", ".join(missing))

    lines = [
        "// Generated by scripts/uicons.py. Do not edit by hand; add icons with",
        "// `python scripts/uicons.py <name>`.",
        "//",
        f"// Outlines of Flaticon UIcons, regular rounded ({PACKAGE}),",
        f"// drawn on a {em}x{em} box. Uicons by Flaticon: https://www.flaticon.com/uicons",
        "",
        f"export const UICON_VIEWBOX = \"0 0 {em} {em}\";",
        "",
        "export const UICON_PATHS = {",
    ]
    for name in names:
        pen = CompactPathPen(glyphs, em)
        glyphs[f"fi-rr-{name}"].draw(pen)
        lines.append(f'  "{name}": "{pen.path()}",')
    lines += ["} as const;", "", "export type UiconName = keyof typeof UICON_PATHS;", ""]

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"{len(names)} icons -> {os.path.relpath(OUT, ROOT)} ({os.path.getsize(OUT) // 1024} KB)")


if __name__ == "__main__":
    main()
