// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbtgkklhdhgwxtzbcvgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhidGdra2xoZGhnd3h0emJjdmdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQyOTk3NTUsImV4cCI6MjA4OTg3NTc1NX0.sAW1J8XMk7OA8jLElzwaZUxJhVYVg2Xp3A-W1RTN11w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});